### ISSUE TITLE
screenshots

### ISSUE THREAD

**Issue by danilo-augusto** [danilo-augusto/vim-afterglow#1]
<img width="577" alt="python" src="https://cloud.githubusercontent.com/assets/8104631/23351038/fa507c26-fcbe-11e6-96c0-fde9ef7df2be.png">
<img width="673" alt="html" src="https://cloud.githubusercontent.com/assets/8104631/23351039/fa684702-fcbe-11e6-89b3-eddfc7ba9cc5.png">
<img width="571" alt="latex" src="https://cloud.githubusercontent.com/assets/8104631/23351040/fa7afc12-fcbe-11e6-8ea4-208d05467650.png">
<img width="652" alt="ruby" src="https://cloud.githubusercontent.com/assets/8104631/23351041/fa7ded3c-fcbe-11e6-9b5b-fee10d43613e.png">

**Comment by danilo-augusto** [comment]
<img width="627" alt="ruby" src="https://cloud.githubusercontent.com/assets/8104631/23351154/c99cf856-fcbf-11e6-88f6-857568a7ed8d.png">
<img width="544" alt="latex" src="https://cloud.githubusercontent.com/assets/8104631/23351155/c9b3d7c4-fcbf-11e6-8229-0c50707a98be.png">
<img width="644" alt="html" src="https://cloud.githubusercontent.com/assets/8104631/23351156/c9bd9318-fcbf-11e6-9f49-0dc661c5aad5.png">
<img width="547" alt="python" src="https://cloud.githubusercontent.com/assets/8104631/23351157/c9c22072-fcbf-11e6-8c58-a04e0838ce5c.png">

**Comment by danilo-augusto** [comment]
![Screen Shot 2019-11-01 at 18 23 37](https://user-images.githubusercontent.com/8104631/68043099-cfbc4800-fcd4-11e9-8b9d-2ba0372f4196.png)

**Comment by EternalWinter** [comment]
Hello! Can u tell me what's plugins u used in the last screen? Left seems like default netrw, but right side?

**Comment by danilo-augusto** [comment]
@EternalWinter Sure!

Right side: Tagbar.
Left side is actually NerdTree with some custom parameters ;)

```
let NERDTreeRespectWildIgnore=1
let NERDTreeAutoDeleteBuffer=1
let NERDTreeMinimalUI=1
let NERDTreeShowHidden=1
let g:NERDTreeHighlightFolders=0
let g:NERDTreeHighlightFoldersFullName=0
let g:NERDTreeExactMatchHighlightFullName=0
let g:NERDTreeFileExtensionHighlightFullName=0
let g:NERDTreePatternMatchHighlightFullName=0
```

**Comment by EternalWinter** [comment]
> @EternalWinter Sure!
> 
> Right side: Tagbar.
> Left side is actually NerdTree with some custom parameters ;)
> 
> ```
> let NERDTreeRespectWildIgnore=1
> let NERDTreeAutoDeleteBuffer=1
> let NERDTreeMinimalUI=1
> let NERDTreeShowHidden=1
> let g:NERDTreeHighlightFolders=0
> let g:NERDTreeHighlightFoldersFullName=0
> let g:NERDTreeExactMatchHighlightFullName=0
> let g:NERDTreeFileExtensionHighlightFullName=0
> let g:NERDTreePatternMatchHighlightFullName=0
> ```

ty so much!
