### ISSUE TITLE
less contrast between window and airline status bar when blackout mode on

### ISSUE THREAD

**Issue by frescoraja** [danilo-augusto/vim-afterglow#10]
**Describe the solution you'd like**
when `g:afterglow_blackout=1` is set, could you also make Airline colors `s:ctermAlmostBlack` / `s:guiAlmostBlack` darker so there's less contrast between edit buffers and airline status bar background? .. I like a little contrast so my preference would be something like 233 / #121212 
just a suggestion , thanks for the cool theme

**Comment by danilo-augusto** [comment]
Done. :)
Thanks for the feedback and the suggestion. I used the configuration you proposed. :)
