### ISSUE TITLE
Bold

### ISSUE THREAD

**Issue by marcelsby** [danilo-augusto/vim-afterglow#17]
How i deactivate bold characters?

![image](https://user-images.githubusercontent.com/57691142/68984139-53098d80-07ed-11ea-8ee2-abed9d648521.png)

PS: Ur theme is awesome

**Comment by danilo-augusto** [comment]
Hi Marcel,

Thank you, I'm glad you find it good! 😊

Sadly, there is currently no way to disable bold specifically for the colorscheme.
In the meantime, what you can do (if you are ok with this of course), is to disable bold entirely in your terminal emulator (like iTerm, cf. the screenshot below) or in your GUI-based program (hopefully there will be an option for it).

For terminal emulators though, it would be deactivating bold for the terminal entirely, inside vim or not, so this "fix" is suboptimal, unless you never want to see bold.

![Screen Shot 2019-11-16 at 01 57 15](https://user-images.githubusercontent.com/8104631/68985118-798eef00-0814-11ea-8357-ca9fabdcaf2d.png)

**Comment by marcelsby** [comment]
Thx for the answer, i'm using MacVim. I'll find how to disable bold in it. :)

**Comment by danilo-augusto** [comment]
Nice! I'm closing this issue then. :)
