### ISSUE TITLE
line 293 sg:orange seems to cause a problem

### ISSUE THREAD

**Issue by tjcertified** [danilo-augusto/vim-afterglow#3]
line 293 of /colors/afterglow.vim seems to cause this error:

Error detected while processing function <SNR>23_X:
line    2:
E254: Cannot allocate color #sg:orange

Changing it from "sg:orange" to s:orange seems to fix it, but I don't know if this is what you intended for this color.

**Comment by danilo-augusto** [comment]
You're right, it was a typo! Sorry about that.
It's strange I didn't get any error though. Nice catch.
Last commit (b7c60d4123520050cd2b1aa5377dacaa952ec10d) has it right, so I'm closing for now. 
Don't hesitate to tell me if anything goes wrong.
